### ISSUE TITLE
Great! but are you sure

### ISSUE THREAD

**Issue by whynotme8998** [PR4GM4/xNet-Ameliorated#1]
Are you sure you have tested the library again? This improved version is better than the original xNET library?
Thank you!

**Comment by PR4GM4** [comment]
It depends on your usage case. If your going to be loop checking multiple times, then this one is better. if your doing a few requests every now and then you should probably use the original xNet.
This one is better for CPU and MEM. Original xNet is better for Error handling and knowing what failed.

**Comment by whynotme8998** [comment]
Yes! Thank you very much.
However yesterday I was having an error with gzip
Details:
System.IO.InvalidDataException: 'The magic number in GZip header is not correct. Make sure you are passing in a GZip stream.

I think the xNET root library may not be as effective. An error occurred when I used Parallel.ForEach

**Comment by whynotme8998** [comment]
Have you  a way to overcome the error I just mentioned above

**Comment by PR4GM4** [comment]
That doesnt happpen to me so idk
